version: '3.8'

services:
  email-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ccm-email-service
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ../logs:/app/logs
      - ../.env:/app/.env:ro
    restart: unless-stopped

    # Configuración de red
    networks:
      - ccm-network

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Límites de recursos
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

# Red personalizada para el proyecto CCM
networks:
  ccm-network:
    driver: bridge
    name: ccm-network
